name: Setup
description: Environment setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5

    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: pnpm

    - shell: bash
      run: |
        pnpm install --frozen-lockfile
