name: Setup
description: Environment setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6

    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: pnpm

    - shell: bash
      run: |
        pnpm install --frozen-lockfile
